# Generated by Django 5.0.9 on 2026-08-15 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="حُذف في"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="اسم الصف")),
                (
                    "age_group",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="الفئة العمرية"
                    ),
                ),
                (
                    "children_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="عدد الأطفال"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classrooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعلّمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف",
                "verbose_name_plural": "الصفوف",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="حُذف في"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("STORY", "قصة"),
                            ("GAME", "لعبة"),
                            ("NOTE", "ملاحظة"),
                        ],
                        max_length=8,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        blank=True, max_length=48, verbose_name="معرّف اللعبة"
                    ),
                ),
                (
                    "happened_on",
                    models.DateField(db_index=True, verbose_name="التاريخ"),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="المدة بالدقائق"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المعلّمة"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="classrooms.classroom",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classroom_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجّلته",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classroom_logs",
                        to="stories.story",
                        verbose_name="القصة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل صف",
                "verbose_name_plural": "دفتر الصف",
                "ordering": ["-happened_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["classroom", "-happened_on"],
                        name="classrooms__classro_25ef73_idx",
                    )
                ],
            },
        ),
    ]
