# Generated by Django 5.0.9 on 2026-09-02 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='حُذف في')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم')),
                ('kind', models.CharField(choices=[('esp32', 'ESP32'), ('keypad', 'لوحة أزرار')], default='esp32', max_length=16, verbose_name='النوع')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المالكة')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='حُذف في')),
                ('uid', models.CharField(db_index=True, max_length=64, verbose_name='رقم البطاقة')),
                ('label', models.CharField(max_length=80, verbose_name='المعنى')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'بطاقة',
                'verbose_name_plural': 'البطاقات',
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='devicecard',
            constraint=models.UniqueConstraint(fields=('device', 'uid'), name='uniq_device_card_uid'),
        ),
    ]
