# Generated by Django 5.0.9 on 2026-09-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='حُذف في')),
                ('index', models.PositiveSmallIntegerField(verbose_name='موضع الزرّ')),
                ('role', models.CharField(choices=[('up', 'فوق'), ('down', 'تحت'), ('left', 'يسار'), ('right', 'يمين'), ('select', 'تأكيد')], max_length=16, verbose_name='الدور')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'زرّ',
                'verbose_name_plural': 'الأزرار',
                'ordering': ['index'],
            },
        ),
        migrations.AddConstraint(
            model_name='devicebutton',
            constraint=models.UniqueConstraint(fields=('device', 'index'), name='uniq_device_button_index'),
        ),
    ]
