# Generated by Django 5.0.9 on 2026-08-15 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="حُذف في"
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        db_index=True, max_length=48, verbose_name="معرّف اللعبة"
                    ),
                ),
                (
                    "game_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="اسم اللعبة"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="المدة بالثواني"
                    ),
                ),
                (
                    "completed_items",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="عناصر أُنجزت"
                    ),
                ),
                (
                    "total_items",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="إجمالي العناصر"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="classrooms.classroom",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بدأتها",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة لعب",
                "verbose_name_plural": "جلسات اللعب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["classroom", "-created_at"],
                        name="games_games_classro_6b96af_idx",
                    )
                ],
            },
        ),
    ]
