# Generated by Django 5.0.9 on 2026-08-15 00:10

import apps.stories.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="حُذف في"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=80,
                        unique=True,
                        verbose_name="المعرّف",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="منشورة"
                    ),
                ),
                (
                    "story_json",
                    models.JSONField(default=dict, verbose_name="بيانات القصة"),
                ),
                (
                    "layout_json",
                    models.JSONField(default=dict, verbose_name="بيانات التخطيط"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="النسخة"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالكة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قصة",
                "verbose_name_plural": "القصص",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="حُذف في"
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(max_length=32, verbose_name="معرّف الأصل"),
                ),
                (
                    "alias",
                    models.CharField(max_length=80, verbose_name="الاسم المستعار"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("images", "صورة"),
                            ("audio", "صوت"),
                            ("spritesheets", "ورقة رسوم"),
                        ],
                        default="images",
                        max_length=16,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.stories.models.story_asset_path,
                        verbose_name="الملف",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="الاسم الأصلي"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الحجم بالبايت"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="stories.story",
                        verbose_name="القصة",
                    ),
                ),
            ],
            options={
                "verbose_name": "أصل",
                "verbose_name_plural": "الأصول",
                "ordering": ["kind", "alias"],
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["is_published", "-updated_at"],
                name="stories_sto_is_publ_399133_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storyasset",
            constraint=models.UniqueConstraint(
                fields=("story", "asset_id"), name="uniq_story_asset_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyasset",
            constraint=models.UniqueConstraint(
                fields=("story", "alias"), name="uniq_story_alias"
            ),
        ),
    ]
