# Generated by Django 5.0.9 on 2026-08-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyasset",
            name="content_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=400,
                verbose_name="المسار داخل القصة",
            ),
        ),
    ]
